copyright: Oliver Salzburg and Kitten Science Contributors
dev_addr: 0.0.0.0:8000
docs_dir: docs
edit_uri: edit/main/docs/current/
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kitten-science/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde
  - toc:
      permalink: true
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search
repo_name: kitten-science/kitten-scientists
repo_url: https://github.com/kitten-science/kitten-scientists
site_name: Kitten Science
site_url: https://kitten-science.com/
theme:
  custom_dir: overrides
  favicon: assets/images/favicon.ico
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  icon:
    repo: fontawesome/brands/github
  logo: assets/images/organization-logo64.png
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: amber
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: indigo
      primary: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation:
      - Quick Start: installation/quick-start.md
      - Minified Builds: installation/minified-builds.md
      - Containers: installation/containers.md
  - User Interface:
      - Overview: sections/overview.md
      - Bonfire: sections/bonfire.md
      - Village: sections/village.md
      - Science: sections/science.md
      - Workshop: sections/workshop.md
      - Resource Control: sections/resource-control.md
      - Trade: sections/trade.md
      - Religion: sections/religion.md
      - Space: sections/space.md
      - Time: sections/time.md
      - Time Control: sections/time-control.md
      - Log Filters: sections/log-filters.md
      - State Management: sections/state-management.md
      - Internals: sections/internals.md
  - Advanced:
      - Kitten DnA: advanced/dna.md
  - Development:
      - Getting Started: development/development.md
      - Development Container: development/devcontainer.md
  - Hall of Honor: hall-of-honor.md
