{
 "title": "Kittens",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kg_resource_value,instance)"
    }
   },
   {
    "name": "location",
    "label": "Location",
    "query": {
     "query": "label_values(kg_resource_value{instance=\"$instance\"},location)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resets",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kg_resets_total{location=\"$location\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Paragon (all time & current)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "kg_paragon_total{type=\"all_time\", location=\"$location\", instance=\"$instance\"}",
     "legendFormat": "All Time"
    },
    {
     "expr": "kg_resource_value{name=\"paragon\", location=\"$location\", instance=\"$instance\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Kittens",
   "type": "timeseries",
   "description": "How many kittens are currently alive?",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kg_resource_value{location=\"$location\", name=\"kittens\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time Crystals",
   "type": "timeseries",
   "description": "How many time crystals are currently in stock?",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kg_resource_value{location=\"$location\", name=\"timeCrystal\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "KS Iteration p99 Details",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg by(le, manager) (rate(ks_iterate_duration_bucket{manager!=\"all\", location=\"$location\", instance=\"$instance\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kg_transcendence_tier{location=\"$location\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Craft Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 5 },
   "targets": [
    {
     "expr": "rate(kg_crafts_total{type=\"current\", location=\"$location\", instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unobtainium",
   "type": "timeseries",
   "description": "How much unobtainium is currently in stock?",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kg_resource_value{location=\"$location\", name=\"unobtainium\", instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Resources",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(label) (kg_resource_value{craftable=\"false\", location=\"$location\", instance=\"$instance\"})",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Craftables",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(label) (kg_resource_value{craftable=\"true\", location=\"$location\", instance=\"$instance\"})",
     "legendFormat": "{{label}}"
    }
   ]
  },
  { "title": "Buildings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Bonfire",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(label) (kg_building_value{tab=\"bonfire\", location=\"$location\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Religion",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(label) (kg_building_value{tab=\"religion\", location=\"$location\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "max by(label) (kg_building_value{tab=\"space\", location=\"$location\", instance=\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}