compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: error
  - code: YN0060
    level: error

nmMode: hardlinks-local

nodeLinker: node-modules
