compressionLevel: 0

defaultSemverRangePrefix: ""

enableTelemetry: false

nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/git-hooks.cjs
    spec: git-hooks

yarnPath: .yarn/releases/yarn-4.0.2.cjs
