version: "3.7"

services:
  backend:
    build:
      context: ../..
      dockerfile: packages/kitten-analysts/backend.Containerfile
    expose:
      # KGNet Interface
      - "7780/tcp"
      # Prometheus Exporter
      - "9091/tcp"
      # Kitten Analysts Websocket
      - "9093/udp"

    volumes:
      - type: bind
        source: packages/kitten-analysts/examples
        target: /local_storage
        read_only: false

  # Actual Kittens Game instance
  game:
    build:
      context: ../..
      dockerfile: packages/kitten-analysts/game.Containerfile
    expose:
      # Kittens Game Browser UI
      - "9080/tcp"
    volumes:
      - type: bind
        source: packages/kitten-analysts/output
        target: /kittensgame/kitten-analysts
        read_only: true
      - type: bind
        source: packages/kitten-engineers/output
        target: /kittensgame/kitten-engineers
        read_only: true
      - type: bind
        source: packages/kitten-scientists/output
        target: /kittensgame/kitten-scientists
        read_only: true

  # Headless container
  ui:
    build:
      context: ../..
      dockerfile: packages/kitten-analysts/ui.Containerfile
    volumes:
      - type: bind
        source: packages/kitten-analysts/examples
        target: /local_storage
        read_only: false
