import { cwarn } from "../tools/Log";
import { GamePage, Upgrade } from "../types";
import { difference, SettingsSection, SettingToggle } from "./SettingsSection";

export type UpgradeSettingsItem = SettingToggle;
export class UpgradeSettings extends SettingsSection {
  items: {
    [item in Upgrade]: UpgradeSettingsItem;
  } = {
    advancedAutomation: { enabled: true },
    advancedRefinement: { enabled: true },
    aiBases: { enabled: true },
    aiEngineers: { enabled: true },
    alloyArmor: { enabled: true },
    alloyAxe: { enabled: true },
    alloyBarns: { enabled: true },
    alloySaw: { enabled: true },
    alloyWarehouses: { enabled: true },
    amBases: { enabled: true },
    amDrive: { enabled: true },
    amFission: { enabled: true },
    amReactors: { enabled: true },
    amReactorsMK2: { enabled: true },
    assistance: { enabled: true },
    astrolabe: { enabled: true },
    astrophysicists: { enabled: true },
    augumentation: { enabled: true },
    automatedPlants: { enabled: true },
    barges: { enabled: true },
    biofuel: { enabled: true },
    bolas: { enabled: true },
    cadSystems: { enabled: true },
    caravanserai: { enabled: true },
    carbonSequestration: { enabled: true },
    cargoShips: { enabled: true },
    celestialMechanics: { enabled: true },
    chronoEngineers: { enabled: true },
    chronoforge: { enabled: true },
    coalFurnace: { enabled: true },
    coldFusion: { enabled: true },
    combustionEngine: { enabled: true },
    compositeBow: { enabled: true },
    concreteBarns: { enabled: true },
    concreteHuts: { enabled: true },
    concreteWarehouses: { enabled: true },
    crossbow: { enabled: true },
    cryocomputing: { enabled: true },
    darkEnergy: { enabled: true },
    deepMining: { enabled: true },
    distorsion: { enabled: true },
    electrolyticSmelting: { enabled: true },
    eludiumCracker: { enabled: true },
    eludiumHuts: { enabled: true },
    eludiumReflectors: { enabled: true },
    energyRifts: { enabled: true },
    enrichedThorium: { enabled: true },
    enrichedUranium: { enabled: true },
    factoryAutomation: { enabled: true },
    factoryLogistics: { enabled: true },
    factoryOptimization: { enabled: true },
    factoryProcessing: { enabled: true },
    factoryRobotics: { enabled: true },
    fluidizedReactors: { enabled: true },
    fluxCondensator: { enabled: true },
    fuelInjectors: { enabled: true },
    geodesy: { enabled: true },
    gmo: { enabled: true },
    goldOre: { enabled: true },
    hubbleTelescope: { enabled: true },
    huntingArmor: { enabled: true },
    hydroPlantTurbines: { enabled: true },
    internet: { enabled: true },
    invisibleBlackHand: { enabled: true },
    ironAxes: { enabled: true },
    ironHoes: { enabled: true },
    ironwood: { enabled: true },
    lhc: { enabled: true },
    logistics: { enabled: true },
    longRangeSpaceships: { enabled: true },
    machineLearning: { enabled: true },
    mineralAxes: { enabled: true },
    mineralHoes: { enabled: true },
    miningDrill: { enabled: true },
    mWReactor: { enabled: true },
    nanosuits: { enabled: true },
    neuralNetworks: { enabled: true },
    nuclearPlants: { enabled: true },
    nuclearSmelters: { enabled: true },
    offsetPress: { enabled: true },
    oilDistillation: { enabled: true },
    oilRefinery: { enabled: true },
    orbitalGeodesy: { enabled: true },
    oxidation: { enabled: true },
    photolithography: { enabled: true },
    photovoltaic: { enabled: true },
    pneumaticPress: { enabled: true },
    printingPress: { enabled: true },
    pumpjack: { enabled: true },
    pyrolysis: { enabled: true },
    qdot: { enabled: true },
    railgun: { enabled: true },
    reactorVessel: { enabled: true },
    refrigeration: { enabled: true },
    register: { enabled: true },
    reinforcedBarns: { enabled: true },
    reinforcedSaw: { enabled: true },
    reinforcedWarehouses: { enabled: true },
    relicStation: { enabled: true },
    rotaryKiln: { enabled: true },
    satelliteRadio: { enabled: true },
    satnav: { enabled: true },
    seti: { enabled: true },
    silos: { enabled: true },
    solarSatellites: { enabled: true },
    spaceEngineers: { enabled: true },
    spaceManufacturing: { enabled: true },
    spiceNavigation: { enabled: true },
    starlink: { enabled: true },
    stasisChambers: { enabled: true },
    steelArmor: { enabled: true },
    steelAxe: { enabled: true },
    steelPlants: { enabled: true },
    steelSaw: { enabled: true },
    stoneBarns: { enabled: true },
    storageBunkers: { enabled: true },
    strenghtenBuild: { enabled: true },
    tachyonAccelerators: { enabled: true },
    thinFilm: { enabled: true },
    thoriumEngine: { enabled: true },
    thoriumReactors: { enabled: true },
    titaniumAxe: { enabled: true },
    titaniumBarns: { enabled: true },
    titaniumMirrors: { enabled: true },
    titaniumSaw: { enabled: true },
    titaniumWarehouses: { enabled: true },
    turnSmoothly: { enabled: true },
    unicornSelection: { enabled: true },
    unobtainiumAxe: { enabled: true },
    unobtainiumDrill: { enabled: true },
    unobtainiumHuts: { enabled: true },
    unobtainiumReflectors: { enabled: true },
    unobtainiumSaw: { enabled: true },
    uplink: { enabled: true },
    voidAspiration: { enabled: true },
    voidEnergy: { enabled: true },
    voidReactors: { enabled: true },
  };

  static validateGame(game: GamePage, settings: UpgradeSettings) {
    const inSettings = Object.keys(settings.items);
    const inGame = game.workshop.upgrades.map(upgrade => upgrade.name);

    const missingInSettings = difference(inGame, inSettings);
    const redundantInSettings = difference(inSettings, inGame);

    for (const upgrade of missingInSettings) {
      cwarn(`The workshop upgrade '${upgrade}' is not tracked in Kitten Scientists!`);
    }
    for (const upgrade of redundantInSettings) {
      cwarn(`The workshop upgrade '${upgrade}' is not an upgrade in Kitten Game!`);
    }
  }
}
