FROM docker.io/library/node:22.17.1-bookworm@sha256:9e6918e8e32a47a58ed5fb9bd235bbc1d18a8c272e37f15d502b9db9e36821ee

LABEL "org.opencontainers.image.description"="Kitten Scientists Development Container"

ARG REPO=https://github.com/nuclear-unicorn/kittensgame.git
ARG BRANCH=master
ARG COMMIT=76d681f1257fc7a7cf70b4212674b6bab269bc79

EXPOSE 8080
EXPOSE 8086

RUN git clone --branch "$BRANCH" --single-branch "$REPO" \
  && cd kittensgame \
  && git checkout "$COMMIT" \
  && yarn add -D @oliversalzburg/js-utils cheerio watch-http-server

WORKDIR /kittensgame
COPY "devcontainer/overlay/*" "./overlay/"
COPY "output/devcontainer/*" "./mod/"
RUN [ "chmod", "+x", "mod/entrypoint-devcontainer.mjs" ]

CMD [ "/bin/bash", "-c", "mod/entrypoint-devcontainer.mjs" ]
