FROM docker.io/library/node:26.9.0-bookworm@sha256:acb7243cabea678dc927ec9020c633d3d82b37b86b1bbcd49dd3f95f6b77ba89

LABEL "org.opencontainers.image.description"="Kitten Scientists Development Container"

ARG REPO=https://github.com/nuclear-unicorn/kittensgame.git
ARG BRANCH=master
ARG COMMIT=master

EXPOSE 8080
EXPOSE 8086

RUN git config --global http.version HTTP/1.1 \
  && git clone --branch "$BRANCH" --single-branch "$REPO" \
  && cd kittensgame \
  && git checkout "$COMMIT" \
  && npm add --save-dev @oliversalzburg/js-utils cheerio watch-http-server

WORKDIR /kittensgame
COPY "devcontainer/overlay/*" "./overlay/"
COPY "output/entrypoint-devcontainer.mjs" "./mod/"
RUN [ "chmod", "+x", "mod/entrypoint-devcontainer.mjs" ]

CMD [ "/bin/bash", "-c", "mod/entrypoint-devcontainer.mjs" ]
