FROM docker.io/library/node:22.17.0-bookworm@sha256:2fa6c977460b56d4d8278947ab56faeb312bc4cc6c4cf78920c6de27812f51c5

LABEL "org.opencontainers.image.description"="Kitten Scientists Development Container"

ARG REPO=https://github.com/nuclear-unicorn/kittensgame.git
ARG BRANCH=master
ARG COMMIT=76d681f1257fc7a7cf70b4212674b6bab269bc79

EXPOSE 8080
EXPOSE 8086

RUN git clone --branch "$BRANCH" --single-branch "$REPO" \
  && cd kittensgame \
  && git checkout "$COMMIT" \
  && yarn add -D @oliversalzburg/js-utils cheerio watch-http-server

WORKDIR /kittensgame
COPY "devcontainer/overlay/*" "./overlay/"
COPY "output/devcontainer/*" "./mod/"
RUN [ "chmod", "+x", "mod/entrypoint-devcontainer.mjs" ]

CMD [ "/bin/bash", "-c", "mod/entrypoint-devcontainer.mjs" ]
