name: Nightly

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:
    inputs:
      move-tags:
        default: false
        description: Allow tags to be moved? Requires GitHub Release.
        required: false
        type: boolean
      publish-documentation:
        default: false
        description: Update the documentation website?
        required: false
        type: boolean
      publish-github-release:
        default: false
        description: Create a GitHub release?
        required: false
        type: boolean
      publish-oci:
        default: false
        description: Publish container?
        type: boolean
        required: false
      release-tag:
        default: nightly
        description: Floating pre-release tag to use.
        type: string
        required: true

concurrency:
  group: nightly
  cancel-in-progress: false

env:
  NODE_VERSION: "24.14.0"

jobs:
  params:
    name: Determine configuration
    outputs:
      move-tags: ${{ github.event_name == 'workflow_dispatch' && inputs.move-tags || 'true' }}
      publish-documentation: ${{ github.event_name == 'workflow_dispatch' && inputs.publish-documentation || 'true' }}
      publish-github-release: ${{ github.event_name == 'workflow_dispatch' && inputs.publish-github-release || 'true' }}
      publish-oci: ${{ github.event_name == 'workflow_dispatch' && inputs.publish-oci || 'true' }}
      release-tag: ${{ github.event_name == 'workflow_dispatch' && inputs.release-tag || 'nightly' }}
      release-channel: nightly
    permissions:
      contents: none
    runs-on: ubuntu-24.04
    steps:
      - if: false
        name: Noop
        run: exit 0

  changelog:
    name: Changelog
    needs:
      - params
    outputs:
      has-changed: ${{ 0 < steps.changelog.outputs.major-total || 0 < steps.changelog.outputs.minor-total || 0 < steps.changelog.outputs.patch-total }}
      version: ${{ steps.changelog.outputs.version-nightly-extended }}
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
          sparse-checkout: package.json
          sparse-checkout-cone-mode: false

      - id: version
        name: Extract current version
        run: echo "root-version=$(jq --raw-output '.version' package.json)" >> $GITHUB_OUTPUT

      - id: changelog
        name: Generate changelog
        uses: oliversalzburg/action-automatic-semantic-releases@v3.3.2
        with:
          automatic-release-tag: ${{ needs.params.outputs.release-tag }}
          changelog-artifact: changelog.json
          dry-run: true
          publish: false
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          root-version: ${{ steps.version.outputs.root-version }}

      - name: Store changelog
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: changelog.json
          path: changelog.json

  skip:
    if: success() && needs.changelog.outputs.has-changed == 'false'
    name: Skip
    needs:
      - changelog
    runs-on: ubuntu-24.04
    steps:
      - name: Print skip reason
        run: echo "No behavior changes since the last nightly were detected."

  qa:
    if: success() && needs.changelog.outputs.has-changed
    name: 🔹 QA
    needs:
      - changelog
    uses: ./.github/workflows/qa.yml

  publish-devcontainer:
    if: success() && needs.params.outputs.publish-oci == 'true' && needs.changelog.outputs.has-changed == 'true'
    name: Publish Devcontainer
    needs:
      - changelog
      - params
      - qa
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Select Node.js version
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: |
          make devcontainer

      - id: meta
        name: Extract metadata
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ghcr.io/kitten-science/devcontainer
          labels: |
            org.opencontainers.image.description=Kitten Science Development Container
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ github.server_url }}/kitten-science/kitten-scientists
            org.opencontainers.image.title=devcontainer
            org.opencontainers.image.version=v${{ needs.changelog.outputs.version }}
          tags: |
            type=raw,value=v${{ needs.changelog.outputs.version }}
            type=raw,value=${{ needs.params.outputs.release-tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

      - name: Log in to the registry
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - env:
          DOCKER_BUILD_RECORD_UPLOAD: false
          DOCKER_BUILD_SUMMARY: false
          SOURCE_DATE_EPOCH: 0
        id: build
        name: Build ${{ needs.params.outputs.move-tags == 'true' && '+ Push' || '' }}
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/cache,mode=max
          context: .
          file: devcontainer/Containerfile
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: ${{ needs.params.outputs.move-tags == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}

      - id: details
        name: Result
        run: |
          DIST_URL="https://ghcr.io/kitten-science/devcontainer:${{ needs.params.outputs.release-tag }}"
          PUBLISH_URL="https://ghcr.io/kitten-science/devcontainer:v${{ needs.changelog.outputs.version }}"
          echo "publish-url=$PUBLISH_URL" >> "$GITHUB_OUTPUT"
          echo "Published OCI to <$PUBLISH_URL>" >> $GITHUB_STEP_SUMMARY
          echo "Tagged OCI as <$DIST_URL>" >> $GITHUB_STEP_SUMMARY

  publish-documentation:
    if: success() && needs.params.outputs.publish-documentation == 'true' && needs.changelog.outputs.has-changed == 'true'
    name: 🔹 Publish
    needs:
      - changelog
      - params
      - qa
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/publish-documentation.yml
    with:
      publish-url: https://kitten-science.com

  nightly:
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
      && needs.changelog.outputs.has-changed == 'true'
    name: Nightly
    needs:
      - changelog
      - params
      - publish-devcontainer
      - publish-documentation
      - qa
    permissions:
      actions: write
      attestations: write
      contents: write
      id-token: write
      packages: write
      pull-requests: read
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Select Node.js version
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org

      - name: Load cached dependencies
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node{{ env.NODE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node${{ env.NODE_VERSION }}

      - name: Build release
        env:
          RELEASE_CHANNEL: ${{ needs.params.outputs.release-channel }}
          RELEASE_VERSION: ${{ needs.changelog.outputs.version }}
        run: make

      - name: Download changelog
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: changelog.json

      - if: success() && needs.params.outputs.publish-github-release == 'true'
        name: Generate GitHub release
        uses: oliversalzburg/action-automatic-semantic-releases@v3.3.2
        with:
          automatic-release-tag: ${{ needs.params.outputs.release-tag }}
          body-suffix: |

            ---
            - Release generated by <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}>
            ${{ needs.publish-documentation.outputs.publish-url && format('- Documentation published at <{0}>', needs.publish-documentation.outputs.publish-url) }}
            ${{ needs.publish-devcontainer.outputs.publish-url && format('- Devcontainer published at <{0}>', needs.publish-devcontainer.outputs.publish-url) }}
          changelog-artifact: changelog.json
          draft: false
          dry-run: ${{ needs.params.outputs.move-tags == 'false' }}
          files: output/*.user.js
          merge-similar: true
          prerelease: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          title: Nightly Build v${{ needs.changelog.outputs.version }}
          with-authors: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::022327457572:role/kitten-science-us0-maintainer
          role-session-name: GitHubActions

      - name: Deploy to S3
        run: |
          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key latest.js \
            --cache-control "public, s-maxage=300" \
            --content-type "text/javascript" \
            --body output/kitten-scientists.inject.js || true
          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key kitten-scientists.user.js \
            --cache-control "public, s-maxage=300" \
            --content-type "text/javascript" \
            --body output/kitten-scientists.user.js || true
          aws s3api put-object \
            --bucket kitten-science-us0 \
            --key kitten-scientists.meta.js \
            --cache-control "public, s-maxage=300" \
            --content-type "text/javascript" \
            --body output/kitten-scientists.meta.js || true
