name: QA

on:
  pull_request:
  push:
    branches:
      - "**"
      - "!main"
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qa:
    name: Lint / Build
    permissions:
      contents: read
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Run make
        run: |
          make lint
          make all
